### ISSUE TITLE
ভাই জিতসেন 

### ISSUE THREAD

**Issue by ShawonAshraf** [anirudha-ani/TestingElectron#1]
ভাই জিতসেন

**Comment by anirudha-ani** [comment]
ভাইরে ভাই Issue তে এসেও হামলা ! 

![image](https://user-images.githubusercontent.com/13461833/102078185-af960c80-3e34-11eb-90b6-798c1e9919a4.png)

**Comment by ShawonAshraf** [comment]
হামলা একটি চলমান প্রক্রিয়া। :P
